using System;
using System.Collections.Generic;

namespace DAL.Models
{
    public partial class JvConfigurationTbl
    {
        public long JvConfigurationId { get; set; }
        public long? PropertyId { get; set; }
        public long? GeneralCashierAccountNumberId { get; set; }
        public long? SalaryClearanceAccountNumberId { get; set; }
        public long? SalaryTaxAccountNumberId { get; set; }
        public string SalaryJournalType { get; set; }
        public long? ServiceChargeAccountNumberId { get; set; }
        public long? ServiceChargeClearanceAccountNumberId { get; set; }
        public long? ServiceChargeTaxAccountNumberId { get; set; }
        public string ServiceChargeJournalType { get; set; }
        public long? EmployeeInsuranceAccountNumberId { get; set; }
        public long? CompanyInsuranceCreditAccountNumberId { get; set; }
        public long? CompanyInsuranceDebitAccountNumberId { get; set; }
        public string InsuranceJournalType { get; set; }
        public bool? UseRiskYn { get; set; }
        public double? RiskRate { get; set; }
        public long? RiskAccountNumberId { get; set; }
        public long? RiskClearanceAccountNumberId { get; set; }
        public string RiskJournalType { get; set; }
        public long? VacationAccountNumberId { get; set; }
        public long? VacationClearanceAccountNumberId { get; set; }
        public string VacationJournalType { get; set; }
        public long? TicketAccountNumberId { get; set; }
        public long? TicketClearanceAccountNumberId { get; set; }
        public string TicketJournalType { get; set; }
        public long? EosAccountNumberId { get; set; }
        public long? EosClearanceAccountNumberId { get; set; }
        public string EosJournalType { get; set; }
        public long? AdditionalPaymentClearanceAccountNumberId { get; set; }
        public string AdditionalPaymentJournalType { get; set; }
        public long? BonusAccountNumberId { get; set; }
        public long? BonusClearanceAccountNumberId { get; set; }
        public string BonusJournalType { get; set; }
        public long? ProfitAccountNumberId { get; set; }
        public long? ProfitClearanceAccountNumberId { get; set; }
        public string ProfitJournalType { get; set; }
        public byte? PropertyCodeType { get; set; }
        public string PropertyTCode { get; set; }
        public string PropertyPosition { get; set; }
        public byte? PropertyStartIndex { get; set; }
        public byte? BranchCodeType { get; set; }
        public string BranchTCode { get; set; }
        public string BranchPosition { get; set; }
        public byte? BranchStartIndex { get; set; }
        public byte? DivisionCodeType { get; set; }
        public string DivisionTCode { get; set; }
        public string DivisionPosition { get; set; }
        public byte? DivisionStartIndex { get; set; }
        public byte? DepartmentCodeType { get; set; }
        public string DepartmentTCode { get; set; }
        public string DepartmentPosition { get; set; }
        public byte? DepartmentStartIndex { get; set; }
        public byte? UnitCodeType { get; set; }
        public string UnitTCode { get; set; }
        public string UnitPosition { get; set; }
        public byte? UnitStartIndex { get; set; }
        public byte? SectionCodeType { get; set; }
        public string SectionTCode { get; set; }
        public string SectionPosition { get; set; }
        public byte? SectionStartIndex { get; set; }
        public byte? GradeCodeType { get; set; }
        public string GradeTCode { get; set; }
        public string GradePosition { get; set; }
        public byte? GradeStartIndex { get; set; }
        public string InsertUserId { get; set; }
        public DateTime? InsertDate { get; set; }
        public string UpdateUserId { get; set; }
        public DateTime? UpdateDate { get; set; }
        public long? MachineId { get; set; }
        public long? FormId { get; set; }
        public long? HolidayAccountNumberId { get; set; }
        public long? HolidayClearanceAccountNumberId { get; set; }
        public string HolidayJournalType { get; set; }
        public long? DayOffAccountNumberId { get; set; }
        public long? DayOffClearanceAccountNumberId { get; set; }
        public string DayOffJournalType { get; set; }
        public long? ImsInsuranceAccountNumberId { get; set; }
        public long? ImsInsuranceClearanceAccountNumberId { get; set; }
        public string ImsInsuranceJournalType { get; set; }
        public double? ImsInsuranceAmount { get; set; }
        public long? IqamaRenewalAccountNumberId { get; set; }
        public long? IqamaRenewalClearanceAccountNumberId { get; set; }
        public string IqamaRenewalJournalType { get; set; }
        public double? IqamaRenewalAmount { get; set; }
        public long? IqamaMedicalAccountNumberId { get; set; }
        public long? IqamaMedicalClearanceAccountNumberId { get; set; }
        public string IqamaMedicalJournalType { get; set; }
        public double? IqamaMedicalAmount { get; set; }
        public long? SchoolFeesAccountNumberId { get; set; }
        public long? SchoolFeesClearanceAccountNumberId { get; set; }
        public string SchoolFeesJournalType { get; set; }
        public long? HealthInsuranceAccountNumberId { get; set; }
        public long? HealthInsuranceClearanceAccountNumberId { get; set; }
        public string HealthInsuranceJournalType { get; set; }
        public long? LifeInsuranceAccountNumberId { get; set; }
        public long? LifeInsuranceClearanceAccountNumberId { get; set; }
        public string LifeInsuranceJournalType { get; set; }
        public long? BaladyaCardAccountNumberId { get; set; }
        public long? BaladyaCardClearanceAccountNumberId { get; set; }
        public string BaladyaCardJournalType { get; set; }
        public long? ExitEntryAccountNumberId { get; set; }
        public long? ExitEntryClearanceAccountNumberId { get; set; }
        public string ExitEntryJournalType { get; set; }
        public double? ExitEntryAmount { get; set; }
        public long? EosAccrualAccountNumberId { get; set; }
        public long? EosAccrualClearanceAccountNumberId { get; set; }
        public string EosAccrualJournalType { get; set; }
        public long? EosAccrualRuleId { get; set; }
        public long? IncentiveBonusAccountNumberId { get; set; }
        public long? IncentiveBonusClearanceAccountNumberId { get; set; }
        public string IncentiveBonusJournalType { get; set; }
        public long? StaffBonusAccountNumberId { get; set; }
        public long? StaffBonusClearanceAccountNumberId { get; set; }
        public string StaffBonusJournalType { get; set; }
        public long? PensionSchemeAccountNumberId { get; set; }
        public long? PensionSchemeClearanceAccountNumberId { get; set; }
        public string PensionSchemeJournalType { get; set; }
    }
}
